library(argparse)

# create a parser closure for input arguments
breedhs_parser <- argument_parser(
    argument_def('breedhs', type = 'character', default_val = 'breedhs',
        help = 'arbitrary positional argument included to enable argument parsing'),
    argument_def('--pop', type = 'character', required = FALSE,
        help = 'the population being analyzed: the population to merge pedigree info into'),
    argument_def('--n_pairs', type = 'integer', required = FALSE,
        help = 'the number of desired breeder pairs (usually 70)'),
    argument_def('--inputs', type = 'character', required = FALSE,
        help = 'the inputs directory path that holds pedigree maps and pedigree history files'),
    argument_def('--ped_map', type = 'character', required = FALSE,
        help = 'path to the pedigree map (csv denoting how overlapping pedigree generations correspond)'),
    argument_def('--hsw_to_wfu', type = 'character', required = FALSE,
        help = 'path to the HSW --> WFU exchange history'),
    argument_def('--wfu_to_hsw', type = 'character', required = FALSE,
        help = 'path to the WFU --> HSW exchange history'),
    argument_def('--peds_dir', type = 'character', required = FALSE, 
        help = 'path to the upper directory for pedigrees'),
    argument_def('--hsw_stem', type = 'character', required = FALSE,
        help = 'the file stem name for formatted HSW pedigrees'),
    argument_def('--hsw_raw_stem', type = 'character', required = FALSE,
        help = 'the file stem name for raw HSW pedigrees'),
    argument_def('--hsw_first_gen', type = 'integer', required = FALSE,
        help = 'the first HSW generation to include in the pedigree'),
    argument_def('--hsw_last_gen', type = 'integer', required = FALSE,
        help = 'the most recent HSW generation to include in the pedigree'),
    argument_def('--wfu_raw_ped', type = 'character', required = FALSE,
        help = 'the file path to the complete raw WFU pedigree'),
    argument_def('--hsw_id_map', type = 'character', required = TRUE,
        help = 'the file path to the HSW ID map'),
    argument_def('--wfu_id_map', type = 'character', required = TRUE,
        help = 'the file path to the WFU ID map'),
    argument_def('--wfu_stem', type = 'character', required = FALSE,
        help = 'the file stem name for formatted WFU pedigrees'),
    argument_def('--wfu_raw_stem', type = 'character', required = FALSE,
        help = 'the file stem name for raw WFU pedigrees'),
    argument_def('--wfu_first_gen', type = 'integer', required = FALSE,
        help = 'the first WFU generation to include in the pedigree'),
    argument_def('--wfu_last_gen', type = 'integer', required = FALSE,
        help = 'the most recent WFU generation to include in the pedigree'),
    argument_def('--generation', type = 'integer', required = FALSE,
        help = 'generic generation variable to accommodate a specific desired generation'),
    argument_def('--utils', type = 'character', required = FALSE,
        help = 'path to the main breedHS.R script'),
    argument_def('--avail_ids', type = 'character', required = FALSE,
        help = 'the path to the file listing animal IDs available for pairing'),
    argument_def('--replace_ids', type = 'character', required = FALSE,
        help = 'the path to the file listing animal IDs that need replacement for pairing'),
    argument_def('--pairs_proposed', type = 'character', required = FALSE,
        help = 'path to the original proposed pairings file produced before colony pairing'),
    argument_def('--proj_dir', type = 'character', required = FALSE,
        help = 'the path to the top directory for the current breeders generation'),
    argument_def('--colony_df', type = 'character', required = FALSE,
        help = 'path to the most recent HSW colony dataframe of ALL rats (not only breeders)'),
    argument_def('--prev_pairs', type = 'character', required = FALSE,
        help = 'path to the previous generations FINAL pairings file'),
    argument_def('--prev_colony_df', type = 'character', required = FALSE,
        help = 'path to the previous generations HSW colony dataframe of ALL rats (not only breeders)'),
    argument_def('--hsw_assignments', type = 'character', required = FALSE,
        help = 'path to HSW assignments file'),
    argument_def('--arg_parser', type = 'character', required = TRUE,
        help = 'path to the argument parser R script'),
    argument_def('--kinship_file', type = 'character', required = FALSE,
        help = 'path to a kinship matrix in csv format'),
    argument_def('--proposed_pairs_file', type = 'character', required = FALSE,
        help = 'path to a proposed pairings file in csv format')

)
