library(argparse)

# create a parser closure for input arguments
breedhs_parser <- argument_parser(
    argument_def('breedhs', type = 'character', default_val = 'breedhs',
        help = 'arbitrary positional argument included to enable argument parsing'),
    argument_def('--peds_dir', type = 'character', required = TRUE, 
        help = 'path to the upper directory for pedigrees'),
    argument_def('--hsw_raw_ped', type = 'character', required = TRUE,
        help = 'the file path to the complete raw HSW pedigree'),
    argument_def('--hsw_stem', type = 'character', required = TRUE,
        help = 'the file stem name for formatted HSW pedigrees'),
    argument_def('--hsw_raw_stem', type = 'character', required = TRUE,
        help = 'the file stem name for raw HSW pedigrees'),
    argument_def('--hsw_first_gen', type = 'integer', required = TRUE,
        help = 'the first HSW generation to include in the pedigree'),
    argument_def('--hsw_last_gen', type = 'integer', required = TRUE,
        help = 'the most recent HSW generation to include in the pedigree'),
    argument_def('--wfu_raw_ped', type = 'character', required = TRUE,
        help = 'the file path to the complete raw WFU pedigree'),
    argument_def('--wfu_stem', type = 'character', required = TRUE,
        help = 'the file stem name for formatted WFU pedigrees'),
    argument_def('--wfu_raw_stem', type = 'character', required = TRUE,
        help = 'the file stem name for raw WFU pedigrees'),
    argument_def('--wfu_first_gen', type = 'integer', required = TRUE,
        help = 'the first WFU generation to include in the pedigree'),
    argument_def('--wfu_last_gen', type = 'integer', required = TRUE,
        help = 'the most recent WFU generation to include in the pedigree'),
    argument_def('--wfu_id_map', type = 'character', required = TRUE,
        help = 'the most recent ID map for the WFU pedigree'),
    argument_def('--hsw_id_map', type = 'character', required = TRUE,
        help = 'the most recent ID map for the HSW pedigree'),
    argument_def('--hsw_assignments', type = 'character', required = TRUE,
        help = 'path to HSW assignments file'),
    argument_def('--prev_colony_df', type = 'character', required = TRUE,
        help = 'path to the previous generations HSW colony dataframe'),
    argument_def('--utils', type = 'character', required = TRUE,
        help = 'path to the main breedHS.R script'),
    argument_def('--proj_dir', type = 'character', required = TRUE,
        help = 'the path to the top directory for the current breeders generation'),
    argument_def('--arg_parser', type = 'character', required = TRUE,
        help = 'path to the argument parser R script')

)
